apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: audio-0717-rhoai 
  janus-idp.io/tekton: audio-0717-rhoai
  backstage.io/kubernetes-id: audio-0717-rhoai
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: audio-0717-rhoai
resources: 
- application-dev.yaml