---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: audio-0717-rhoai
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audio-0717-rhoai 
  name: audio-0717-rhoai
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi