apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: audio-0717-rhoai
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audio-0717-rhoai 
  name: audio-0717-rhoai
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: audio-0717-rhoai 
